// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//   sqlc-gen-java 0.0.7

package com.example.video_segmenter_api.infrastructure.orchestrator.persistence.sqlc;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Optional;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

@Generated("io.github.tandemdude.sqlc-gen-java")
public class Queries {
    private final java.sql.Connection conn;

    public Queries(java.sql.Connection conn) {
        this.conn = conn;
    }


    private static final String getVideoById = """
        -- name: GetVideoById :one
        SELECT id, file_path, status
        FROM videos
        WHERE id = ?
        """;

    public record GetVideoByIdRow(
        @NonNull String id,
        @NonNull String filePath,
        @NonNull String status
    ) {}

    public Optional<GetVideoByIdRow> getVideoById(
        @NonNull String id
    ) throws SQLException {
        var stmt = conn.prepareStatement(getVideoById);
        stmt.setString(1, id);

        var results = stmt.executeQuery();
        if (!results.next()) {
            return Optional.empty();
        }

        var ret = new GetVideoByIdRow(
            results.getString(1),
            results.getString(2),
            results.getString(3)
        );
        if (results.next()) {
            throw new SQLException("expected one row in result set, but got many");
        }

        return Optional.of(ret);
    }

    private static final String insertVideo = """
        -- name: InsertVideo :exec
        INSERT INTO videos (id, file_path, status)
        VALUES (?, ?, ?)
        """;

    public void insertVideo(
        @NonNull String id,
        @NonNull String filePath,
        @NonNull String status
    ) throws SQLException {
        var stmt = conn.prepareStatement(insertVideo);
        stmt.setString(1, id);
        stmt.setString(2, filePath);
        stmt.setString(3, status);

        stmt.execute();
    }

    private static final String updateVideoStatus = """
        -- name: UpdateVideoStatus :exec
        UPDATE videos
        SET status = ?
        WHERE id = ?
        """;

    public void updateVideoStatus(
        @NonNull String id,
        @NonNull String status
    ) throws SQLException {
        var stmt = conn.prepareStatement(updateVideoStatus);
        stmt.setString(1, id);
        stmt.setString(2, status);

        stmt.execute();
    }
}
